# DEPRECATED
version: '3.1'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.3.16
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
  apache:
    image: glad2os/agu-practical:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: "mariadb"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      SMTP_PASSWORD: ""
      SMTP_USERNAME: ""
    links:
      - mariadb
