apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-volume
  labels:
    app: online-presentations
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: online-presentations-volume
  labels:
    app: online-presentations
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi